Document: feedingit
Title: Debian feedingit Manual
Author: <insert document author here>
Abstract: This manual describes what feedingit is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/feedingit/feedingit.sgml.gz

Format: postscript
Files: /usr/share/doc/feedingit/feedingit.ps.gz

Format: text
Files: /usr/share/doc/feedingit/feedingit.text.gz

Format: HTML
Index: /usr/share/doc/feedingit/html/index.html
Files: /usr/share/doc/feedingit/html/*.html

  
